# Generated by Django 4.0.5 on 2022-06-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_remove_project_user_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Author',
            new_name='author',
        ),
    ]
