# Generated by Django 4.0.5 on 2022-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0008_remove_project_user_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('django', 'DJANGO'), ('java', 'JAVA'), ('flask', 'FLASK'), ('python', 'PYTHON')], default='python', max_length=6),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
